### ISSUE TITLE
Inconsistent function signatures in PyBricks 2.0 API: EV3Brick.speaker.play_file(file_name=...); DriveBase.drive(drive_speed=...)

### ISSUE THREAD

**Issue by TheVinhLuong102** [pybricks/pybricks-api#23]
Hi @laurensvalk @dlech, it seems the following function signatures are inconsistent between the PyBricks 2.0 API and the pybricks-micropython interpreter:

Pybricks 2.0 API: EV3Brick.speaker.play_file(file_name=...) vs.
pybricks-micropython: EV3Brick.speaker.play_file(file=...)

Pybricks 2.0 API: DriveBase.drive(drive_speed=...) vs.
pybricks-micropython: DriveBase.drive(speed=...)

Thank you.

**Comment by laurensvalk** [comment]
Good catch, thanks! I can confirm the mismatch in the source coe.

**Comment by TheVinhLuong102** [comment]
@laurensvalk that's great. Could you let me know which set of signatures is the right one going forward?

**Comment by laurensvalk** [comment]
We haven't decided yet. The ones in the API are (were intended to be) correct, but since the 2.0 release is already out, we'll have to rethink if it makes sense to change the implementation at this point.

If you're worried about script compatibility, you can just omit using the keywords for now.

**Comment by TheVinhLuong102** [comment]
Ok @laurensvalk. Let's keep this issue open till the next release then?

**Comment by laurensvalk** [comment]
This is fixed in https://github.com/pybricks/pybricks-api/commit/82b16dc8de8064baa1af9ca8e7adf70081f9469e and https://github.com/pybricks/pybricks-api/commit/55c4c86c237e9fd5fcaec90d63957bd733f6d6ff. Thank you for reporting!

**Comment by TheVinhLuong102** [comment]
thank you @laurensvalk :)

**Comment by TheVinhLuong102** [comment]
Hi @laurensvalk, @dlech,

Just some minor stuff: the auto-complete signature for `DriveBase.drive(...)` -- e.g., on VSCode -- continues to show the `drive_speed=...` argument, instead of just `speed=...`.

Please see the attached screenshot.

Thank you.

Vinh

<img width="760" alt="Screen Shot 2021-07-30 at 13 04 43" src="https://user-images.githubusercontent.com/7796578/127706416-9fb7d033-520f-4e84-a32b-770eadbfdcfc.png">

**Comment by dlech** [comment]
The `pybricks` package is out of date. There is an issue for this: https://github.com/pybricks/pybricks-api/issues/73

**Comment by TheVinhLuong102** [comment]
Hi @dlech,

We're actually using the bleeding-edge master branch (by `python3 -m pip install https://GitHub.com/PyBricks/PyBricks-API/archive/master.zip`) and that is still showing.

Vinh

**Comment by dlech** [comment]
OK, best to open a new issue then instead of commenting on a closed one.
